version: "3.6"

services:
    rabbitmq:
        image: rabbitmq:3.11-management
        container_name: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./dados:/var/lib/rabbitmq/
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
    dfmysql:
      image: mysql:8.0.33
      volumes:
        - /home/tslima/Documentos/alura/docker/mysql:/var/lib/mysql
      ports:
      - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: root